### ISSUE TITLE
Example sending signals

### ISSUE THREAD

**Issue by timknapen** [opentok/opentok-linux-sdk-samples#11]
Hi, is there example code/ documentation on how to do signaling similar in the web/js SDK? see: https://github.com/opentok/opentok-web-samples/tree/master/Signaling

**Comment by joliveraortega** [comment]
Thanks for filling this issue @timknapen. We are about to merge PR https://github.com/opentok/opentok-linux-sdk-samples/pull/9 where we are adding a signaling sample along with a few others. Stay tuned!

**Comment by timknapen** [comment]
great, thanks! I saw your branch https://github.com/joliveraortega/opentok-linux-sdk-samples/tree/OPENTOK-40778 that has the signaling example. I was hoping to port it for Mac OSX, but it doesn't look trivial to me.
