### ISSUE TITLE
Glibc-2.27 Ubuntu 18.04 Support

### ISSUE THREAD

**Issue by JohnBetaCode** [opentok/opentok-linux-sdk-samples#14]
We're having troubles building the example publisher-only from your [SDK](https://tokbox.com/developer/sdks/linux/) for an x86_64 (adm64)  system with Ubuntu 18.04, and for this one, only Glibc-2.28 is supported, and the compiling process is asking for the 2.28 version, 

could you provide support to Ubuntu 18.04 or older versions of  Glibc?

**Comment by msach22** [comment]
@JohnBetaCode At this time, Ubuntu is not a supported platform. We've relayed this feedback to our product team so they can see if we can add support.

**Comment by charlielito** [comment]
With Ubuntu 20.04 it works like a charm,  you can use the binaries
