### ISSUE TITLE
Publisher error. Error code: Timed out while attempting to publish

### ISSUE THREAD

**Issue by vijayrakesh13** [opentok/opentok-linux-sdk-samples#18]
Hi,

I'm trying to run Basic Video Chat demo application and on other side I had connected as a subscriber with same session id on opentok playground, but I get an error as mentioned below.

> on_session_connected callback function
> Publisher error. Error code: Timed out while attempting to publish.
> corrupted size vs. prev_size
> Aborted

Regards,
VR

**Comment by vijayrakesh13** [comment]
Any suggestions?

**Comment by vijayrakesh13** [comment]
Any suggestions?

**Comment by vijayrakesh13** [comment]
@MichaelJolley @robjperez @joliveraortega @jaoo

**Comment by joliveraortega** [comment]
@vijayrakesh13 Thanks for trying the OpenTok Linux SDK. Would you be able to enable console logging and share the logs you get when trying to publish please. That would help us a lot. Video capturing might be failing for your camera.

**Comment by vijayrakesh13** [comment]
@joliveraortega Please find the attached log. [Tokbox_Log.txt](https://github.com/opentok/opentok-linux-sdk-samples/files/5936021/Tokbox_Log.txt)

**Comment by vijayrakesh13** [comment]
@joliveraortega Any information from logs?

**Comment by joliveraortega** [comment]
Please, start capturing looks much earlier please. By the time you start publishing at least. You captured logs when it is too late. Thanks.

**Comment by vijayrakesh13** [comment]
@joliveraortega Here is the attached log from beginning. 
[Log.txt.log](https://github.com/opentok/opentok-linux-sdk-samples/files/5942894/Log.txt.log)

**Comment by joliveraortega** [comment]
I see the other endpoint does not support video (according its SDP):
```
m=video 0 UDP/TLS/RTP/SAVPF 0
```
What's the other endpoint?, could you try a different one please?

I see video capturing seems to work (not audio though).

**Comment by vijayrakesh13** [comment]
Other endpoint is opentok playground with Google Chrome Version 88.0.4324.146

**Comment by vijayrakesh13** [comment]
@joliveraortega  As an other endpoint I had tried on different system with same opentok playground on chrome browser, but I get same issue. In stream Information `has video` is `true`.

**Comment by joliveraortega** [comment]
In your logs I see this is a routed session and the Linux endpoint is able to send video (`m=video 9 UDP/TLS/RTP/SAVPF 96 97 100 101 102`) however the platform (the SFU) is says no video from it (`m=video 0 UDP/TLS/RTP/SAVPF 0`). Let me ask with some colleagues working on the platform side. I see no issues from the client point of view.

**Comment by vijayrakesh13** [comment]
Ok thanks, I'll wait for your reply.

**Comment by joliveraortega** [comment]
Sure. Can you try other endpoint in the meantime (e.g. Linux to Linux) please? Thanks.

**Comment by vijayrakesh13** [comment]
@joliveraortega I had tried that too with opentok playground on Firefox v85.0, but same issue.

**Comment by joliveraortega** [comment]
I would try another endpoint that is not using the JS SDK (e.g. another app using the Linux SDK, or another app using any of our other native SDKs (Android, Windows, etc) and instead trying a routed session I would try a relayed one. Can you do that please? Thanks.

**Comment by vijayrakesh13** [comment]
@joliveraortega I downloaded Tokbox android/iOS application to test, but doesn't have support for manual session ID. Is there any other option to test readily?

**Comment by joliveraortega** [comment]
There are other public sample apps you can use either for Android (https://github.com/opentok/opentok-android-sdk-samples)or iOS (https://github.com/opentok/opentok-ios-sdk-samples).

**Comment by vijayrakesh13** [comment]
@joliveraortega  Just now checked with iOS SDK and I still get same issue.

**Comment by joliveraortega** [comment]
So you are not able to join a session in OpenTok playground tool where you could see the stream coming from the iOS endpoint. Is that correct?

**Comment by vijayrakesh13** [comment]
@joliveraortega No, I have created a stream from Linux platform and published to iOS SDK (in routed session), but at receiver end we got blank screen. Now again, I have created relayed session from Linux to JS SDK (opentok playground) and I can able see the video stream(with lagging).

**Comment by joliveraortega** [comment]
- Try a relayed session between Linux and iOS. 

- It seem you have some kind of issue with routed sessions. It might be because some kind of misconfiguration. Is it your account all setup?. Try another API KEY for routed sessions please.

**Comment by joliveraortega** [comment]
Just had some news from the folks working on the platform side. It seems the API KEY you are using does not allow VP8/VP9 as valid video codecs. You have to allow them in the API KEY configuration or just use a new API KEY where they (at least VP8) is a valid/permitted video codec.

**Comment by vijayrakesh13** [comment]
Ok, Let me check and update you.

**Comment by vijayrakesh13** [comment]
@joliveraortega  Thank you! It's working.

**Comment by vijayrakesh13** [comment]
@joliveraortega  Forgot to ask, how to change the video source? By default, it is taking from video0 I might need to change sometimes to video1. I had gone through the documentation, but couldn't find any.

**Comment by joliveraortega** [comment]
Nope. There is no a way to select the video device file so the SDK picks up the first available. The only option you have is to build a custom video capturer where you read video frames from wherever you want. Implementing your own video capturer is not a trivial task. There is a very simple sample in this repo https://github.com/opentok/opentok-linux-sdk-samples/tree/master/Custom-Video-Capturer but it just a skeleton about what needs to be implemented. This sample app does not capture video frames from a camera but it just create fake video frames and provide them.

**Comment by vijayrakesh13** [comment]
@joliveraortega Thank you. I had gone through the programming, but I didn't get where to give preferred camera option. I can only find resolution and video format.

**Comment by vijayrakesh13** [comment]
@joliveraortega  Is the const otc_video_capturer *video_capturer  = "/dev/video1" is the pointer to point the capture device?

**Comment by joliveraortega** [comment]
Nope, this is not done that way. You have to build a full custom video capturer and capture video frames from whatever you want/need. Have a look at the sample at https://github.com/opentok/opentok-linux-sdk-samples/tree/master/Custom-Video-Capturer. We do not have an API to select the video device file to use as I commented.

Your requests here are no longer about an issue. We should close this. If you need help with writing a custom video capturer module I guess you should open a ticket with support and continue from there. Thanks.
