### ISSUE TITLE
Building and running Publisher-Only in docker

### ISSUE THREAD

**Issue by chigarovae** [opentok/opentok-linux-sdk-samples#19]
I'm currently attempting to run Publisher-Only sample in docker with image based on debian buster using official dockerfile provided in samples repo with some minor adjustments and my opentok creds in _config.h_ file (such configuration is needed to run publisher within the kubernetes cluster).

Dockerfile as follows:

```
FROM debian:buster

RUN echo "deb http://security.debian.org/ buster/updates main" | tee -a /etc/apt/sources.list

RUN apt-get update \
    && apt-get -yqqf --no-install-recommends install \
       ca-certificates \
       wget \
       gnupg \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

RUN echo "deb https://dl.bintray.com/tokbox/debian buster main" | tee -a /etc/apt/sources.list
RUN wget -O- -q https://bintray.com/user/downloadSubjectPublicKey?username=bintray | apt-key add -

RUN apt-get update \
  && apt-get install -y \
     software-properties-common \
     build-essential \
     cmake \
     clang \
     libc++-dev \
     libc++abi-dev \
     libsdl2-dev \
     libopentok-dev \
     pulseaudio \
     mc \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*

COPY Publisher-Only /samples/Publisher-Only
COPY common /samples/common
COPY scripts /samples/scripts
WORKDIR /samples/scripts

CMD bash -x build.sh
```

mc added just for inspecting within the container, build.sh is adjusted to build only the Publisher-Only binary.

Building succeeds, and i get the _publisher_only_ binary within the _build_ folder, but i'm still unable to run it in any way:

```
/samples/Publisher-Only/build# ./publisher_only 
*********************** OpenTok Linux SDK ****************************
**** Version/Revision: linux_llvm-2.19.0/a9d768b8ead19c9f91a1d99c1641632b7387f5de
**** Library built on: Feb 11 2021
**** Copyright 2021 TokBox, Inc.
**** Licensed under the Apache License, Version 2.0
****
error: XDG_RUNTIME_DIR not set in the environment.
[ERROR] otk_peer_connection.cpp:1938 - Error creating webrtc default AudioDeviceModule
[ERROR] otk_peer_connection.cpp:1073 - otk_peer_connection_static_init failed to initialize.
[ERROR] otk_peer_connection.cpp:1993 - otk_peer_connection_static_init ERROR
```

I tried [this](https://github.com/opentok/opentok-linux-sdk-samples/issues/16#issuecomment-723145737) solution proposed by @joliveraortega from a similar issue, but still without any actual result.

Could you please give a hint what might be wrong?

**Comment by joliveraortega** [comment]
Hello @chigarovae. Thanks for trying the OpenTok Linux SDK samples. You have to create virtual audio input/output sources. The steps at https://github.com/opentok/opentok-linux-sdk-samples/issues/16#issuecomment-723145737 are an example and the should work for you too. Are you sure you are not missing any step? On the other hand you should run https://github.com/opentok/opentok-linux-sdk-samples/tree/master/Custom-Video-Capturer as it includes a capturer that provides fake video frames to stream.

**Comment by chigarovae** [comment]
Hi @joliveraortega and thanks for fast reply! Yes, i tried your solution last week without success, maybe i'm missing something.

That's what i do. First, i build an image with that dockerfile provided in my first comment:

```
docker build ./ --tag=opentok-test
docker tag opentok-test local/opentok-test
```

Second, i run this image in interactive mode and build the publisher-only:

```
docker run --privileged -it local/opentok bash
./build.sh
```

Build succeeds without any warning.

Third, i apply your solution from that your comment inside the running container. Just a notice - i had to use _--system_ to run pulseaudio server as it is being launched in docker that has only root user. Pulseaudio also starts without any warning or error.

After that, i go to build folder, run publisher-only binary, and get that error.

I guess i might miss something, but seems i was accurate enough applying your solution.

Thanks for your attention once again!

**Comment by joliveraortega** [comment]
How you create virtual audio input/output sources is out of the scope of the samples. https://github.com/opentok/opentok-linux-sdk-samples/issues/16#issuecomment-723145737 works for us but you might want to try another way. Does audio capturing works for you inside the container? That's what you have to manage. Again, please try the https://github.com/opentok/opentok-linux-sdk-samples/tree/master/Custom-Video-Capturer sample instead the Publisher-Only one. Publisher-Only won't be able to capture any video.

**Comment by v-kpheng** [comment]
Closing, given lack of response and follow up question may be out of scope.
