### ISSUE TITLE
Independent audio samples

### ISSUE THREAD

**Issue by ferjm** [opentok/opentok-linux-sdk-samples#25]
We have this use case where we need to fetch the audio streams of all participants independently, but we see no way to achieve that with the current SDK. Right now, it seems that `otc_audio_device` provides a single audio stream which is a mix of all participants' audio streams, so there's no way to do things like speech-to-text, moderation or any kind of audio processing per participant. I was wondering if there is any way to get independent audio streams, maybe something equivalent to `otc_subscriber_callbacks.on_render_frame` but for audio.

**Comment by joliveraortega** [comment]
Hello! Thanks for trying our OpenTok Linux SDK! Yes, you are right. Right now there is no way to receive audio samples from a given participant independently. There are some workarounds but they are not trivial where you have to spawn a new process for each new subscriber and subscribe to that specific subscriber (only) so the samples you get through the audio device will be only the ones from that specific subscriber. Having a new callback for the subscriber for the audio samples it receives would be great for uses cases like speech-to-text, moderation or any kind of audio processing per participant. Sadly we do not support this yet. Will share this with our product team (cc @Daniel085).

**Comment by ferjm** [comment]
Thanks @joliveraortega is there any workaround with the current SDK to be able to subscribe to every participant's audio stream independently? Maybe run the subscription code per each publisher in a separate process?

**Comment by joliveraortega** [comment]
There is a workaround where you need a process running an instance of app where you connect to a session and wait for stream created events. Once there is one you grab the stream id you get in the callback and you spawn another different process. In that different process you connect again to the session and just subscribe to that participant. Given the audio device acts as a singleton (per process) and there is just one subscriber the audio you get is from that given participant. You repeat this same thing for every new on stream created event and subscribe to that stream in a new process. It is a bit overkill I know but right now it is the only way to get audio samples individually from each stream in the session.

Will ping @Daniel085 again so he shares any input from product whether we are adding a callback for the subscriber for the audio samples it receives in the near future.

**Comment by v-kpheng** [comment]
@ferjm, Linux SDK 2.22.0 adds this new feature.  From https://tokbox.com/developer/sdks/linux/release-notes.html.

<img width="1241" alt="image" src="https://user-images.githubusercontent.com/49660118/192670293-65a969fa-5291-4aa2-b540-67908bd93234.png">

Closing.
