### ISSUE TITLE
Issue: WebRTC issues when using a specific mobile network service provider

### ISSUE THREAD

**Issue by jvech** [opentok/opentok-linux-sdk-samples#32]
**Describe the bug**
We have a fleet of robots which are teleoperated on different parts of the world, to do that we use a SIM card to upload the video to a server which sends that data to the final user through a web application. The video is streamed using webrtc protocol, the problem comes when we use etisalat SIM Cards, when we use them is very hard to get a video session, but
its download and upload speeds are reasonable enough to stream our videos, looking at the logs we found a time out every time we try to connect.

**Screenshots**
![image](https://user-images.githubusercontent.com/64784774/207917994-57b55af3-ec73-4454-815c-ac92034aae51.png)
![image](https://user-images.githubusercontent.com/64784774/207918858-69359878-24ed-44f6-ac28-84874e02180e.png)

**Device (please complete the following information):**
- Linux SDK version: 2.18.0
- OS and version: Ubuntu 22.04

**Comment by v-kpheng** [comment]
Apologies, @jvech, for the belated reply.  Thanks for letting us know about this.

Linux 2.18.0 is no longer supported.  Can you try a more recent version please?
