### ISSUE TITLE
Fatal error in: ../../src/media/engine/adm_helpers.cc, line 38

### ISSUE THREAD

**Issue by ghost** [opentok/opentok-linux-sdk-samples#4]
With both Basic-Video-Chat and Publisher-Only, I have updated main.cpp with the session, token and api values.  Compiles fine following the instructions (running Ubuntu server on GCP, so used the x86_64 package.  When I run the compiled programme I get:

```
#
# Fatal error in: ../../src/media/engine/adm_helpers.cc, line 38
# last system error: 88
# Check failed: 0 == adm->Init() (0 vs. -1)
# Failed to initialize the ADM.Aborted (core dumped)
```

**Comment by MattB98** [comment]
Delving into this more (I last programmed in c / c++ 20 years ago), this looks like an issue with audio devices and webrtc?  Given I'm running this on a gcp virtual server with no soundcard, do I need to set up some kind of dummy audio device?  I have done so for /dev/video0 using v4l2loopback.

**Comment by jaoo** [comment]
Hello @MattB98. Thanks for giving a try to our OpenTok Linux SDK. This issue is somehow expected giving there is no a sound card. There are two options here then: i) disable audio for the publisher/subcriber or ii) implement a custom audio device (a fake one) and using it (check the header file at `opentok/audiodevice.h` for more info please).

**Comment by MattB98** [comment]
Thanks @jaoo.  Sorry, my C skills are really rusty.  I've got a fake device running on /dev/video0.  This is providing both video and audio.  How do I use that device?  Presumably I need to init an audio device before publishing, so I guess I need to call something

**Comment by MattB98** [comment]
Or to ask another way, how do I hack the Publisher-Only example to take audio & video input from /dev/video0 ?

**Comment by jaoo** [comment]
There is no way to set the Linux video device to capture video from. The API is agnostic about the platform. 

In any case the video device at `/dev/video0` seems not to be valid according to https://chromium.googlesource.com/external/webrtc/+/branch-heads/71/media/engine/adm_helpers.cc#38. I would be useful to have a look at the logs. You can enable them (see https://github.com/opentok/opentok-linux-sdk-samples/blob/master/Publisher-Only/CMakeLists.txt#L9) and send them back to me (joseantonio.oliveraortega@vonage.com).

You can implement your own video capturer so you are responsible for capturing video frames from wherever you want (even there is no need for `/dev/videoX` devices). Let me know if you want to know how to implement a custom video capturer.

**Comment by MattB98** [comment]
So when I run Publisher-Only, where is it taking video and audio input from?  This is what I'm trying to solve: https://stackoverflow.com/questions/56339293/rtmp-stream-input-to-an-opentok-session - so how do I pipe raw media if it is not from /dev/videoX?

**Comment by jaoo** [comment]
The SDK tries to capture video from `/dev/videoX` devices but these video devices might not be valid for WebRTC (this is your case I guess but I would need to see the logs I requested). If you want to pipe media you have to implement a custom video capturer (have a look at the header file at `opentok/videocapturer.h`) and a custom audio device (have a look at the header file at `opentok/audiodevice.h`) and use them.

**Comment by jaoo** [comment]
I am going to close this issue given there has not been activity for some time.

**Comment by Matt-B50** [comment]
Apologies, my focus had to move on to other projects, but I'm looking at this again now.  I've built a fresh VM on the Google Cloud platform, and recompiled Publisher-Only.  Same issue (I've not implemented a loopback / fake device yet).  I'll forward the logs and look at https://github.com/opentok/opentok-linux-sdk-samples/issues/4#issuecomment-537832142

**Comment by jaoo** [comment]
@Matt-B50 Pleae file a support ticket an we will take care of this. Thanks.

**Comment by Matt-B50** [comment]
I have done.  I've also setup v4l2loopback on both /dev/video0 and /dev/video1 and get the same error.

**Comment by weijunying2019102969** [comment]
what did you do to solve this problem? It happened to me , too

**Comment by Matt-B50** [comment]
> what did you do to solve this problem? It happened to me , too

Sorry, 4 years is too long ago.  I don't use tokbox any more, it didn't scale for me during the pandemic, so switched to other solutions.
